<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'BaseDirectoryScopedFormatLinter' => 'lint/linter/BaseDirectoryScopedFormatLinter.php',
    'UmidataInnoDBTabLinter' => 'lint/linter/UmidataInnoDBTabLinter.php',
    'UmidataMySQLArcanistConfiguration' => 'arcanist/UmidataMySQLArcanistConfiguration.php',
    'UmidataMySQLArcanistLandcastleWorkflow' => 'workflows/UmidataMySQLArcanistLandcastleWorkflow.php',
    'UmidataMySQLAssertUsageLinter' => 'lint/linter/UmidataMySQLAssertUsageLinter.php',
    'UmidataMySQLClangFormatLinter' => 'lint/linter/UmidataMySQLClangFormatLinter.php',
    'UmidataMySQLLintEngine' => 'lint/UmidataMySQLLintEngine.php',
    'UmidataMySQLLinter' => 'lint/linter/UmidataMySQLLinter.php',
    'UmidataMySQLPrintfLinter' => 'lint/linter/UmidataMySQLPrintfLinter.php',
    'UmidataMySQLTestResultLinter' => 'lint/linter/UmidataMySQLTestResultLinter.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'BaseDirectoryScopedFormatLinter' => 'ArcanistLinter',
    'UmidataInnoDBTabLinter' => 'ArcanistLinter',
    'UmidataMySQLArcanistConfiguration' => 'ArcanistConfiguration',
    'UmidataMySQLArcanistLandcastleWorkflow' => 'ArcanistBaseWorkflow',
    'UmidataMySQLAssertUsageLinter' => 'ArcanistLinter',
    'UmidataMySQLClangFormatLinter' => 'BaseDirectoryScopedFormatLinter',
    'UmidataMySQLLintEngine' => 'ArcanistLintEngine',
    'UmidataMySQLLinter' => 'ArcanistLinter',
    'UmidataMySQLPrintfLinter' => 'ArcanistLinter',
    'UmidataMySQLTestResultLinter' => 'ArcanistLinter',
    'UmidataMySQLWhitespaceLinter' => 'ArcanistLinter',
  ),
));
